version: 0.1.{build}

clone_folder: c:\projects\qbdi

shallow_clone: true

configuration:
  - Release

environment:
  PYTHON: "C:\\Python35-x64"
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  CMAKE_TEMPLATE: Visual Studio 16 2019
  matrix:
    - arch_vcvarsall: X64
      qbdi_arch: X86_64
      qbdi_plateform: WINDOWS
    - arch_vcvarsall: X86
      qbdi_arch: X86
      qbdi_plateform: WINDOWS


cache:
  - deps\llvm\%qbdi_plateform%-%qbdi_arch%\lib -> deps\llvm\build.py
  - deps\llvm\%qbdi_plateform%-%qbdi_arch%\include -> deps\llvm\build.py

install:
  # Install Python (from the official .msi of https://python.org) and pip when
  # not already installed.
  #- ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - cmd: mkdir build
  - cmd: cd build

build_script:
  - "\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat\" %arch_vcvarsall%"
  - cmd: cmake .. -G "Ninja" -DCMAKE_CROSSCOMPILING=FALSE -DCMAKE_BUILD_TYPE=%configuration% -DQBDI_PLATFORM=%qbdi_plateform% -DQBDI_ARCH=%qbdi_arch% -DQBDI_EXAMPLES=ON
  - ps: if (-not((Test-Path("../deps/llvm/$env:qbdi_plateform-$env:qbdi_arch/lib")) -and (Test-Path("../deps/llvm/$env:qbdi_plateform-$env:qbdi_arch/include")))) { python ..\deps\llvm\build.py prepare "$env:qbdi_plateform-$env:qbdi_arch" ; python ..\deps\llvm\build.py build "$env:qbdi_plateform-$env:qbdi_arch" ; python ..\deps\llvm\build.py package "$env:qbdi_plateform-$env:qbdi_arch" }
  - cmd: python ..\deps\llvm\build.py clean %qbdi_plateform%-%qbdi_arch%
  - cmd: cmake .. -G "Ninja" -DCMAKE_CROSSCOMPILING=FALSE -DCMAKE_BUILD_TYPE=%configuration% -DQBDI_PLATFORM=%qbdi_plateform% -DQBDI_ARCH=%qbdi_arch% -DQBDI_EXAMPLES=ON
  - cmd: ninja

after_build:
  - cmd: cpack

test_script:
  - cmd: c:\projects\qbdi\build\test\QBDItest
  - cmd: c:\projects\qbdi\build\test\QBDIBenchmark

artifacts:
  - name: Installer
    path: 'build\QBDI-*.exe'
