version: 0.1.{build}

clone_folder: c:\projects\qbdi

shallow_clone: true

configuration:
  - Release

environment:
  PYTHON: "C:\\Python35-x64"
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  CMAKE_TEMPLATE: Visual Studio 16 2019
  matrix:
    - platform: X64
      qbdi_plateform: win-X86_64
    - platform: X86
      qbdi_plateform: win-X86


cache:
  - deps\llvm\%qbdi_plateform%\lib -> deps\llvm\build.py
  - deps\llvm\%qbdi_plateform%\include -> deps\llvm\build.py
  - deps\gtest\%qbdi_plateform%\lib -> deps\gtest\%qbdi_plateform%\build.py
  - deps\gtest\%qbdi_plateform%\include -> deps\gtest\%qbdi_plateform%\build.py

install:
  # Install Python (from the official .msi of https://python.org) and pip when
  # not already installed.
  #- ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - cmd: mkdir build
  - cmd: cd build

build_script:
  - "\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat\" %Platform%"
  - cmd: cmake .. -G "Ninja" -DCMAKE_CROSSCOMPILING=FALSE -DCMAKE_BUILD_TYPE=%configuration% -DPLATFORM=%qbdi_plateform% -DEXAMPLES=TRUE
  - ps: if (-not((Test-Path("../deps/llvm/$env:qbdi_plateform/lib")) -and (Test-Path("../deps/llvm/$env:qbdi_plateform/include")))) { python ..\deps\llvm\build.py prepare "$env:qbdi_plateform" ; python ..\deps\llvm\build.py build "$env:qbdi_plateform" ; python ..\deps\llvm\build.py package "$env:qbdi_plateform" }
  - cmd: python ..\deps\llvm\build.py clean %qbdi_plateform%
  - ps: if (-not((Test-Path("../deps/gtest/$env:qbdi_plateform/lib")) -and (Test-Path("../deps/gtest/$env:qbdi_plateform/include")))) { ninja -v gtest }
  - cmd: python ..\deps\gtest\%qbdi_plateform%\build.py clean %qbdi_plateform%
  - cmd: cmake .. -G "Ninja" -DCMAKE_CROSSCOMPILING=FALSE -DCMAKE_BUILD_TYPE=%configuration% -DPLATFORM=%qbdi_plateform% -DEXAMPLES=TRUE
  - cmd: ninja

test_script:
  - cmd: c:\projects\qbdi\build\test\Release\QBDItest

after_build:
  - cmd: cpack

artifacts:
  - name: Installer
    path: 'build\QBDI-*.exe'
