language: cpp 

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
  packages:
    - g++
    - ccache
  homebrew:
    packages:
      - ccache

linux_target: &linux_target
  os: linux
  dist: xenial
  compiler: gcc
  env:
    - QBDI_PLATFORM="LINUX"
    - QBDI_ARCH="X86_64"

linux_target32: &linux_target32
  os: linux
  dist: xenial
  compiler: gcc
  env:
    - QBDI_PLATFORM="LINUX"
    - QBDI_ARCH="X86"

osx_target: &osx_target
  os: osx
  osx_image: xcode9.4
  env:
    - QBDI_PLATFORM="OSX"
    - QBDI_ARCH="X86_64"
    - CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release -DCMAKE_CROSSCOMPILING=FALSE -DQBDI_PLATFORM=${QBDI_PLATFORM} -DQBDI_ARCH=${QBDI_ARCH} -DQBDI_TOOLS_VALIDATOR=TRUE -DQBDI_EXAMPLES=TRUE"

osx_target32: &osx_target32
  os: osx
  osx_image: xcode9.4
  env:
    - QBDI_PLATFORM="OSX"
    - QBDI_ARCH="X86"
    - CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release -DCMAKE_CROSSCOMPILING=FALSE -DQBDI_PLATFORM=${QBDI_PLATFORM} -DQBDI_ARCH=${QBDI_ARCH} -DQBDI_TOOLS_VALIDATOR=TRUE -DQBDI_EXAMPLES=TRUE"

install_llvm: &install_llvm
  script:
    - mkdir build && cd build
    - cmake .. ${CMAKE_ARGS}
    - eval '[[ -n "$(find ../deps/llvm/${QBDI_PLATFORM}-${QBDI_ARCH}/lib -type f -print -quit)" && -n "$(find ../deps/llvm/${QBDI_PLATFORM}-${QBDI_ARCH}/include -type f -print -quit)" ]] || make llvm'
  before_cache:
    # Reduce cache size
    - python3 ../deps/llvm/build.py clean ${QBDI_PLATFORM}-${QBDI_ARCH}

docker_llvm: &docker_llvm
  services:
    - docker
  script:
    - bash ./docker/travis_linux/llvm.sh

compile_and_test: &compile_and_test
  script:
    - mkdir build && cd build
    - cmake .. ${CMAKE_ARGS}
    - make -j2
    - ./test/QBDITest

docker_compile_and_test: &docker_compile_and_test
  services:
    - docker
  script:
    - bash ./docker/travis_linux/qbdi.sh

cache:
  - apt
  - ccache

cache:
  directories:
    - deps/llvm/LINUX-X86_64/include
    - deps/llvm/LINUX-X86_64/lib
    - deps/llvm/LINUX-X86/include
    - deps/llvm/LINUX-X86/lib
    - deps/llvm/OSX-X86_64/include
    - deps/llvm/OSX-X86_64/lib
    - deps/llvm/OSX-X86/include
    - deps/llvm/OSX-X86/lib
    - tools/validation_runner/travis_db

sudo: required

jobs:
  include:
    - stage: deps_llvm
      <<: *osx_target
      <<: *install_llvm
    - stage: deps_llvm
      <<: *osx_target32
      <<: *install_llvm
    - stage: deps_llvm
      <<: *linux_target
      <<: *docker_llvm
    - stage: deps_llvm
      <<: *linux_target32
      <<: *docker_llvm

    - stage: qbdi
      <<: *osx_target
      <<: *compile_and_test
    - stage: qbdi
      <<: *osx_target32
      <<: *compile_and_test
    - stage: qbdi
      <<: *linux_target
      <<: *docker_compile_and_test
    - stage: qbdi
      <<: *linux_target32
      <<: *docker_compile_and_test
